### ISSUE TITLE
Error The file specified is not a Registry script.

### ISSUE THREAD

**Issue by jfranpino** [zeeter82/plexscan#1]
When executing the original script, ERROR

Cannot import powershell_plexsacan.reg The file specified is not a Registry script. You can only import binary log files from the registry editor

**Comment by zeeter82** [comment]
> 

Make sure you have your .reg file formatted correctly and save it with notepad or another standard txt editor (Notepad++ etc.).


![Screenshot_1](https://github.com/zeeter82/plexscan/assets/17049920/b0425cac-1fee-4fa0-b240-6c4836ab01c0)

**Comment by zeeter82** [comment]
Closing issue, haven't seen any further updates.
